variables:
    Project: 'Azure Pipelines Agent in Docker'

jobs:

  - job: Focal_20_04_Based
    variables:
      OS: Linux
      TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal -t devizervlad/crossplatform-azure-pipelines-agent:latest"
      TAG: focal
      BASE_IMAGE: 'ubuntu:focal'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Bionic_18_04_Based
    variables:
      OS: Linux
      TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic"
      TAG: bionic
      BASE_IMAGE: 'ubuntu:bionic'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_16_04_Based
    variables:
      OS: Linux
      TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial"
      TAG: xenial
      BASE_IMAGE: 'ubuntu:xenial'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Buster_10_Based
    variables:
      OS: Linux
      TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster"
      TAG: buster
      BASE_IMAGE: 'debian:buster'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Stretch_9_Based
    variables:
      OS: Linux
      TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch"
      TAG: stretch
      BASE_IMAGE: 'debian:stretch'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Jessie_8_Based
    variables:
      OS: Linux
      TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie"
      TAG: jessie
      BASE_IMAGE: 'debian:jessie'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

# trigger:
#  - master

trigger:
  batch: true
  branches:
    include:
      - master

schedules:
  - cron: "30 3 * * *"
    displayName: 'Nightly rebuild (at 3:30)'
    branches:
      include:
        - master
