variables:
    Project: 'Azure Pipelines Agent in Docker'

jobs:

  - job: Bionic_Based
    variables:
      OS: Linux
      TAG: latest
      BASE_IMAGE: bionic
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_Based
    variables:
      OS: Linux
      TAG: xenial
      BASE_IMAGE: xenial
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml


# trigger:
#  - master

trigger:
  batch: true
  branches:
    include:
      - master

schedules:
  - cron: "30 3 * * *"
    displayName: 'Nightly rebuild (at 3:30)'
    branches:
      include:
        - master
