variables:
    Project: 'Azure Pipelines Agent in Docker'

jobs:

  - job: Ubuntu_18_04
    variables:
      OS: Linux
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml


trigger:
  - master

