variables:
    Project: 'Azure Pipelines Agent in Docker'

jobs:

  - job: BuildX_Docker_Images
    strategy:
      maxParallel: 4
      matrix:
        
        Focal_20_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal -t devizervlad/crossplatform-azure-pipelines-agent:latest"
          TAG: focal
          BASE_IMAGE: 'ubuntu:focal'
        
        Slim_Focal_20_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:focal-slim -t devizervlad/crossplatform-azure-pipelines-agent:latest-slim"
          TAG: focal
          BASE_IMAGE: 'ubuntu:focal'
          SLIM: 'true'
          
        Buster_10_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster"
          TAG: buster
          BASE_IMAGE: 'debian:buster'

        Slim_Buster_10_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:buster-slim"
          TAG: buster
          BASE_IMAGE: 'debian:buster'
          SLIM: 'true'

        Stretch_9_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch"
          TAG: stretch
          BASE_IMAGE: 'debian:stretch'

        Slim_Stretch_9_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:stretch-slim"
          TAG: stretch
          BASE_IMAGE: 'debian:stretch'
          SLIM: 'true'

        Bionic_18_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic"
          TAG: bionic
          BASE_IMAGE: 'ubuntu:bionic'
          
        Slim_Bionic_18_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:bionic-slim"
          TAG: bionic
          BASE_IMAGE: 'ubuntu:bionic'
          SLIM: 'true'

        Xenial_16_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial"
          TAG: xenial
          BASE_IMAGE: 'ubuntu:xenial'
          
        Slim_Xenial_16_04_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:xenial-slim"
          TAG: xenial
          BASE_IMAGE: 'ubuntu:xenial'
          SLIM: 'true'

        Jessie_8_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie"
          TAG: jessie
          BASE_IMAGE: 'debian:jessie'

        Slim_Jessie_8_Based:
          TAGS: "-t devizervlad/crossplatform-azure-pipelines-agent:jessie-slim"
          TAG: jessie
          BASE_IMAGE: 'debian:jessie'
          SLIM: 'true'
          
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-nix.yml

# trigger:
#  - master

trigger:
  batch: true
  branches:
    include:
      - master
      
schedules:
  - cron: "30 3 * * *"
    displayName: 'Nightly rebuild (at 3:30)'
    branches:
      include:
        - master
